FROM python:3.12-slim-buster

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

# 필요한 빌드 명령어 (예시)
# RUN python setup.py build

CMD ["echo", "Docker build completed!"]
