name: AI Project CI

on:
  push:
    branches: [ "develop", "main" ]
    paths:
      - 'AI-kellyn/**'
      - 'AI-mac/**'

  pull_request:
    branches: [ "develop", "main" ]
    paths:
      - 'AI-kellyn/**'
      - 'AI-mac/**'

  workflow_dispatch:
    inputs:
      target_job:
        description: '실행할 Job을 선택하세요'
        required: false
        type: choice
        options:
          - ci-kellyn
          - ci-mac

jobs:
  ci-kellyn:
    name: CI - AI-kellyn
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.target_job == 'ci-kellyn'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./AI-kellyn
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install Dependencies
        run: pip install -r requirements.txt
      #- name: Lint
      #  run: |
      #    pip install flake8
      #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Unit Tests
        run: |
          pip install pytest
          pytest ./tests
      - name: Integration Tests
        run: |
          pip install pytest httpx
          uvicorn main:app --host 0.0.0.0 --port 8000 --background &
          sleep 5
          pytest ./integration_tests
          pkill uvicorn
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile-ai-kellyn
          push: true
          tags: your-dockerhub-username/ai-kellyn:latest # Replace with your Docker Hub username
          cache-from: type=gha,scope=build-ai-kellyn
          cache-to: type=gha,mode=max,scope=build-ai-kellyn

  ci-mac:
    name: CI - AI-mac
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.target_job == 'ci-mac'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./AI-mac
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install Dependencies
        run: pip install -r requirements.txt
      #- name: Lint
      #  run: |
      #    pip install flake8
      #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Unit Tests
        run: |
          pip install pytest
          pytest ./tests
      - name: Integration Tests
        run: |
          pip install pytest httpx
          uvicorn main:app --host 0.0.0.0 --port 8000 --background &
          sleep 5
          pytest ./integration_tests
          pkill uvicorn
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile-ai-mac
          push: true
          tags: your-dockerhub-username/ai-mac:latest # Replace with your Docker Hub username
          cache-from: type=gha,scope=build-ai-mac
          cache-to: type=gha,mode=max,scope=build-ai-mac
