services:
  mysql:
    image: mysql:8.0
    container_name: mysql-develop
    restart: always
    env_file:
      - /home/ubuntu/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - /home/ubuntu/mysql-conf/custom.cnf:/etc/mysql/conf.d/custom.cnf:ro
    networks:
      - internal_network

  redis:
    image: redis/redis-stack:latest
    container_name: redis-develop
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    command: ["redis-server", "/etc/redis/redis-stack.conf"]
    volumes:
      - redis_data:/data
      - /home/ubuntu/redis.conf:/etc/redis/redis-stack.conf
    networks:
      - internal_network

volumes:
  mysql_data:
  redis_data:

networks:
  internal_network:
    driver: bridge
