# 공통 설정
bind 0.0.0.0
protected-mode no
port 6379

# 마스터 또는 슬레이브 역할 분기
# 아래는 slave 인스턴스에서만 적용되도록 템플릿에서 처리할 수 있음
{% if role == "slave" %}
replicaof redis-master.redis.svc.cluster.local 6379
{% endif %}
